# Generated by Django 3.1.5 on 2022-06-05 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.EmailField(max_length=254)),
                ('post', models.URLField()),
                ('creation_date', models.DateField(default=datetime.datetime(2022, 6, 5, 16, 45, 20, 173225))),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
