# Generated by Django 3.1.5 on 2022-06-12 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 12, 15, 17, 0, 717493)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='login',
            field=models.EmailField(default='anonymous', max_length=254),
        ),
    ]
