# Generated by Django 3.1.5 on 2022-06-13 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20220613_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 10, 14, 37, 249116)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='login',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
