# Generated by Django 3.1.5 on 2022-06-13 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20220613_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 16, 49, 29, 382424)),
        ),
    ]
