# Generated by Django 3.1.5 on 2022-06-13 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_auto_20220613_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 16, 51, 37, 312158, tzinfo=utc)),
        ),
    ]
