# Generated by Django 3.1.5 on 2022-06-13 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20220613_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 18, 30, 27, 233469, tzinfo=utc)),
        ),
    ]
