# Generated by Django 3.1.5 on 2022-05-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('login', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('birth_date', models.DateField(default='1970-01-01')),
            ],
        ),
    ]
